// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tribes.sql

package registrydb

import (
	"context"
)

const countTribesWithSlug = `-- name: CountTribesWithSlug :one
SELECT count(*) FROM tribes WHERE slug = ?
`

func (q *Queries) CountTribesWithSlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTribesWithSlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTribe = `-- name: InsertTribe :exec
INSERT INTO tribes (slug, name, file) VALUES (?, ?, ?)
`

type InsertTribeParams struct {
	Slug string
	Name string
	File string
}

func (q *Queries) InsertTribe(ctx context.Context, arg InsertTribeParams) error {
	_, err := q.db.ExecContext(ctx, insertTribe, arg.Slug, arg.Name, arg.File)
	return err
}

const tribeFile = `-- name: TribeFile :one
SELECT file FROM tribes WHERE slug = ?
`

func (q *Queries) TribeFile(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRowContext(ctx, tribeFile, slug)
	var file string
	err := row.Scan(&file)
	return file, err
}

const tribeFiles = `-- name: TribeFiles :many
SELECT file FROM tribes ORDER BY slug
`

func (q *Queries) TribeFiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, tribeFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file string
		if err := rows.Scan(&file); err != nil {
			return nil, err
		}
		items = append(items, file)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tribeSlugs = `-- name: TribeSlugs :many
SELECT slug FROM tribes ORDER BY slug
`

func (q *Queries) TribeSlugs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, tribeSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
