// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package ratelimitdb

import (
	"context"
)

const alertCounts = `-- name: AlertCounts :many
SELECT event, CAST(sum(n) AS INTEGER) AS n FROM alert_counters WHERE slot > ? GROUP BY event
`

type AlertCountsRow struct {
	Event string
	N     int64
}

func (q *Queries) AlertCounts(ctx context.Context, slot string) ([]AlertCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, alertCounts, slot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertCountsRow
	for rows.Next() {
		var i AlertCountsRow
		if err := rows.Scan(&i.Event, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const alertsSent = `-- name: AlertsSent :many
SELECT signal, sent_at FROM alerts_sent
`

func (q *Queries) AlertsSent(ctx context.Context) ([]AlertsSent, error) {
	rows, err := q.db.QueryContext(ctx, alertsSent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertsSent
	for rows.Next() {
		var i AlertsSent
		if err := rows.Scan(&i.Signal, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRepeatedRequests = `-- name: CountRepeatedRequests :one
SELECT count(*) FROM (
    SELECT email_hash FROM code_requests WHERE at > ?1 GROUP BY email_hash HAVING count(*) >= CAST(?2 AS INTEGER)
)
`

type CountRepeatedRequestsParams struct {
	Since       string
	MinRequests int64
}

// The hashes of addresses with at least the given number of requests in the window.
func (q *Queries) CountRepeatedRequests(ctx context.Context, arg CountRepeatedRequestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepeatedRequests, arg.Since, arg.MinRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementAlertCounter = `-- name: IncrementAlertCounter :exec
INSERT INTO alert_counters (slot, event, n) VALUES (?, ?, 1)
ON CONFLICT (slot, event) DO UPDATE SET n = n + 1
`

type IncrementAlertCounterParams struct {
	Slot  string
	Event string
}

func (q *Queries) IncrementAlertCounter(ctx context.Context, arg IncrementAlertCounterParams) error {
	_, err := q.db.ExecContext(ctx, incrementAlertCounter, arg.Slot, arg.Event)
	return err
}

const purgeAlertCounters = `-- name: PurgeAlertCounters :execrows
DELETE FROM alert_counters WHERE slot <= ?
`

func (q *Queries) PurgeAlertCounters(ctx context.Context, slot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAlertCounters, slot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAlertSent = `-- name: SetAlertSent :exec
INSERT INTO alerts_sent (signal, sent_at) VALUES (?, ?)
ON CONFLICT (signal) DO UPDATE SET sent_at = excluded.sent_at
`

type SetAlertSentParams struct {
	Signal string
	SentAt string
}

func (q *Queries) SetAlertSent(ctx context.Context, arg SetAlertSentParams) error {
	_, err := q.db.ExecContext(ctx, setAlertSent, arg.Signal, arg.SentAt)
	return err
}
