// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_requests.sql

package ratelimitdb

import (
	"context"
)

const countCodeRequestsByEmail = `-- name: CountCodeRequestsByEmail :one
SELECT count(*) FROM code_requests WHERE email_hash = ? AND at > ?
`

type CountCodeRequestsByEmailParams struct {
	EmailHash []byte
	At        string
}

func (q *Queries) CountCodeRequestsByEmail(ctx context.Context, arg CountCodeRequestsByEmailParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodeRequestsByEmail, arg.EmailHash, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodeRequestsByIP = `-- name: CountCodeRequestsByIP :one
SELECT count(*) FROM code_requests WHERE ip_hash = ? AND at > ?
`

type CountCodeRequestsByIPParams struct {
	IpHash []byte
	At     string
}

func (q *Queries) CountCodeRequestsByIP(ctx context.Context, arg CountCodeRequestsByIPParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodeRequestsByIP, arg.IpHash, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCodeRequest = `-- name: InsertCodeRequest :exec
INSERT INTO code_requests (at, email_hash, ip_hash) VALUES (?, ?, ?)
`

type InsertCodeRequestParams struct {
	At        string
	EmailHash []byte
	IpHash    []byte
}

func (q *Queries) InsertCodeRequest(ctx context.Context, arg InsertCodeRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertCodeRequest, arg.At, arg.EmailHash, arg.IpHash)
	return err
}

const purgeCodeRequests = `-- name: PurgeCodeRequests :execrows
DELETE FROM code_requests WHERE at <= ?
`

func (q *Queries) PurgeCodeRequests(ctx context.Context, at string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeCodeRequests, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
