// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decoy_codes.sql

package ratelimitdb

import (
	"context"
)

const decoyCode = `-- name: DecoyCode :one
SELECT email_hash, expires_at, attempts_left FROM decoy_codes WHERE email_hash = ?
`

func (q *Queries) DecoyCode(ctx context.Context, emailHash []byte) (DecoyCode, error) {
	row := q.db.QueryRowContext(ctx, decoyCode, emailHash)
	var i DecoyCode
	err := row.Scan(&i.EmailHash, &i.ExpiresAt, &i.AttemptsLeft)
	return i, err
}

const deleteDecoyCode = `-- name: DeleteDecoyCode :exec
DELETE FROM decoy_codes WHERE email_hash = ?
`

func (q *Queries) DeleteDecoyCode(ctx context.Context, emailHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteDecoyCode, emailHash)
	return err
}

const purgeDecoyCodes = `-- name: PurgeDecoyCodes :execrows
DELETE FROM decoy_codes WHERE expires_at <= ? OR attempts_left = 0
`

func (q *Queries) PurgeDecoyCodes(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeDecoyCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replaceDecoyCode = `-- name: ReplaceDecoyCode :exec
INSERT INTO decoy_codes (email_hash, expires_at, attempts_left)
VALUES (?, ?, ?)
ON CONFLICT (email_hash) DO UPDATE SET
    expires_at = excluded.expires_at,
    attempts_left = excluded.attempts_left
`

type ReplaceDecoyCodeParams struct {
	EmailHash    []byte
	ExpiresAt    string
	AttemptsLeft int64
}

func (q *Queries) ReplaceDecoyCode(ctx context.Context, arg ReplaceDecoyCodeParams) error {
	_, err := q.db.ExecContext(ctx, replaceDecoyCode, arg.EmailHash, arg.ExpiresAt, arg.AttemptsLeft)
	return err
}

const setDecoyCodeAttempts = `-- name: SetDecoyCodeAttempts :exec
UPDATE decoy_codes SET attempts_left = ? WHERE email_hash = ?
`

type SetDecoyCodeAttemptsParams struct {
	AttemptsLeft int64
	EmailHash    []byte
}

func (q *Queries) SetDecoyCodeAttempts(ctx context.Context, arg SetDecoyCodeAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, setDecoyCodeAttempts, arg.AttemptsLeft, arg.EmailHash)
	return err
}
