// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratelimitdb

type AlertCounter struct {
	Slot  string
	Event string
	N     int64
}

type AlertsSent struct {
	Signal string
	SentAt string
}

type CodeRequest struct {
	ID        int64
	At        string
	EmailHash []byte
	IpHash    []byte
}

type DecoyCode struct {
	EmailHash    []byte
	RequestHash  []byte
	ExpiresAt    string
	AttemptsLeft int64
}
