// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratelimitdb

type CodeRequest struct {
	ID        int64
	At        string
	Slug      string
	EmailHash []byte
	IpHash    []byte
}

type DecoyCode struct {
	EmailHash    []byte
	ExpiresAt    string
	AttemptsLeft int64
}
