// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert_counters.sql

package tribedb

import (
	"context"
)

const alertCounts = `-- name: AlertCounts :many
SELECT event, CAST(sum(n) AS INTEGER) AS n FROM alert_counters WHERE slot > ? GROUP BY event
`

type AlertCountsRow struct {
	Event string
	N     int64
}

func (q *Queries) AlertCounts(ctx context.Context, slot string) ([]AlertCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, alertCounts, slot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertCountsRow
	for rows.Next() {
		var i AlertCountsRow
		if err := rows.Scan(&i.Event, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAlertCounter = `-- name: IncrementAlertCounter :exec
INSERT INTO alert_counters (slot, event, n) VALUES (?, ?, 1)
ON CONFLICT (slot, event) DO UPDATE SET n = n + 1
`

type IncrementAlertCounterParams struct {
	Slot  string
	Event string
}

func (q *Queries) IncrementAlertCounter(ctx context.Context, arg IncrementAlertCounterParams) error {
	_, err := q.db.ExecContext(ctx, incrementAlertCounter, arg.Slot, arg.Event)
	return err
}

const purgeAlertCounters = `-- name: PurgeAlertCounters :execrows
DELETE FROM alert_counters WHERE slot <= ?
`

func (q *Queries) PurgeAlertCounters(ctx context.Context, slot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAlertCounters, slot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
