// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package tribedb

import (
	"context"
	"database/sql"
)

const auditLog = `-- name: AuditLog :many
SELECT audit_log.id, audit_log.at, audit_log.operation, audit_log.member_id, audit_log.author_id, audit_log.session_id, audit_log.device_type, audit_log.os, audit_log.browser, audit_log.installed_app, members.email AS member_email
FROM audit_log JOIN members ON members.id = audit_log.member_id
ORDER BY audit_log.id
`

type AuditLogRow struct {
	ID           int64
	At           string
	Operation    string
	MemberID     int64
	AuthorID     sql.NullInt64
	SessionID    sql.NullInt64
	DeviceType   sql.NullString
	Os           sql.NullString
	Browser      sql.NullString
	InstalledApp sql.NullInt64
	MemberEmail  sql.NullString
}

func (q *Queries) AuditLog(ctx context.Context) ([]AuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, auditLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLogRow
	for rows.Next() {
		var i AuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Operation,
			&i.MemberID,
			&i.AuthorID,
			&i.SessionID,
			&i.DeviceType,
			&i.Os,
			&i.Browser,
			&i.InstalledApp,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (at, operation, member_id, author_id, session_id, device_type, os, browser, installed_app)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEntryParams struct {
	At           string
	Operation    string
	MemberID     int64
	AuthorID     sql.NullInt64
	SessionID    sql.NullInt64
	DeviceType   sql.NullString
	Os           sql.NullString
	Browser      sql.NullString
	InstalledApp sql.NullInt64
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.At,
		arg.Operation,
		arg.MemberID,
		arg.AuthorID,
		arg.SessionID,
		arg.DeviceType,
		arg.Os,
		arg.Browser,
		arg.InstalledApp,
	)
	return err
}
