// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_requests.sql

package tribedb

import (
	"context"
)

const countCodeRequests = `-- name: CountCodeRequests :one
SELECT count(*) FROM code_requests WHERE at > ?
`

func (q *Queries) CountCodeRequests(ctx context.Context, at string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCodeRequests, at)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCodeRequest = `-- name: InsertCodeRequest :exec
INSERT INTO code_requests (at) VALUES (?)
`

func (q *Queries) InsertCodeRequest(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, insertCodeRequest, at)
	return err
}

const purgeCodeRequests = `-- name: PurgeCodeRequests :execrows
DELETE FROM code_requests WHERE at <= ?
`

func (q *Queries) PurgeCodeRequests(ctx context.Context, at string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeCodeRequests, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
