// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package tribedb

import (
	"context"
)

const deleteLoginCode = `-- name: DeleteLoginCode :exec
DELETE FROM login_codes WHERE member_id = ?
`

func (q *Queries) DeleteLoginCode(ctx context.Context, memberID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLoginCode, memberID)
	return err
}

const loginCode = `-- name: LoginCode :one
SELECT member_id, code_hash, expires_at, attempts_left FROM login_codes WHERE member_id = ?
`

func (q *Queries) LoginCode(ctx context.Context, memberID int64) (LoginCode, error) {
	row := q.db.QueryRowContext(ctx, loginCode, memberID)
	var i LoginCode
	err := row.Scan(
		&i.MemberID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.AttemptsLeft,
	)
	return i, err
}

const purgeLoginCodes = `-- name: PurgeLoginCodes :execrows
DELETE FROM login_codes WHERE expires_at <= ? OR attempts_left = 0
`

func (q *Queries) PurgeLoginCodes(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeLoginCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const replaceLoginCode = `-- name: ReplaceLoginCode :exec
INSERT INTO login_codes (member_id, code_hash, expires_at, attempts_left)
VALUES (?, ?, ?, ?)
ON CONFLICT (member_id) DO UPDATE SET
    code_hash = excluded.code_hash,
    expires_at = excluded.expires_at,
    attempts_left = excluded.attempts_left
`

type ReplaceLoginCodeParams struct {
	MemberID     int64
	CodeHash     []byte
	ExpiresAt    string
	AttemptsLeft int64
}

func (q *Queries) ReplaceLoginCode(ctx context.Context, arg ReplaceLoginCodeParams) error {
	_, err := q.db.ExecContext(ctx, replaceLoginCode,
		arg.MemberID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AttemptsLeft,
	)
	return err
}

const setLoginCodeAttempts = `-- name: SetLoginCodeAttempts :exec
UPDATE login_codes SET attempts_left = ? WHERE member_id = ?
`

type SetLoginCodeAttemptsParams struct {
	AttemptsLeft int64
	MemberID     int64
}

func (q *Queries) SetLoginCodeAttempts(ctx context.Context, arg SetLoginCodeAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, setLoginCodeAttempts, arg.AttemptsLeft, arg.MemberID)
	return err
}
