// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package tribedb

import (
	"context"
	"database/sql"
)

const insertMember = `-- name: InsertMember :one
INSERT INTO members (email, display_name, status, added_at, added_by)
VALUES (?, ?, 'active', ?, ?)
RETURNING id
`

type InsertMemberParams struct {
	Email       sql.NullString
	DisplayName sql.NullString
	AddedAt     string
	AddedBy     sql.NullInt64
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMember,
		arg.Email,
		arg.DisplayName,
		arg.AddedAt,
		arg.AddedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const memberByEmail = `-- name: MemberByEmail :one
SELECT id, email, display_name, status, added_at, added_by, revoked_at, revoked_by FROM members WHERE email = ?
`

func (q *Queries) MemberByEmail(ctx context.Context, email sql.NullString) (Member, error) {
	row := q.db.QueryRowContext(ctx, memberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.AddedAt,
		&i.AddedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const memberByID = `-- name: MemberByID :one
SELECT id, email, display_name, status, added_at, added_by, revoked_at, revoked_by FROM members WHERE id = ?
`

func (q *Queries) MemberByID(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRowContext(ctx, memberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.AddedAt,
		&i.AddedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const revokeMember = `-- name: RevokeMember :execrows
UPDATE members SET status = 'revoked', revoked_at = ?, revoked_by = ?
WHERE id = ? AND status = 'active'
`

type RevokeMemberParams struct {
	RevokedAt sql.NullString
	RevokedBy sql.NullInt64
	ID        int64
}

func (q *Queries) RevokeMember(ctx context.Context, arg RevokeMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeMember, arg.RevokedAt, arg.RevokedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
