// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package tribedb

import (
	"context"
	"database/sql"
)

const insertMember = `-- name: InsertMember :one
INSERT INTO members (email, display_name, status, added_at, added_by)
VALUES (?, ?, 'active', ?, ?)
RETURNING id
`

type InsertMemberParams struct {
	Email       sql.NullString
	DisplayName sql.NullString
	AddedAt     string
	AddedBy     sql.NullInt64
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMember,
		arg.Email,
		arg.DisplayName,
		arg.AddedAt,
		arg.AddedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const memberByEmail = `-- name: MemberByEmail :one
SELECT id, email, display_name, status, added_at, added_by, revoked_at, revoked_by FROM members WHERE email = ?
`

func (q *Queries) MemberByEmail(ctx context.Context, email sql.NullString) (Member, error) {
	row := q.db.QueryRowContext(ctx, memberByEmail, email)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.AddedAt,
		&i.AddedBy,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}
