// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tribedb

import (
	"database/sql"
)

type AuditLog struct {
	ID           int64
	At           string
	Operation    string
	MemberID     int64
	AuthorID     sql.NullInt64
	SessionID    sql.NullInt64
	DeviceType   sql.NullString
	Os           sql.NullString
	Browser      sql.NullString
	InstalledApp sql.NullInt64
}

type CodeRequest struct {
	ID int64
	At string
}

type LoginCode struct {
	MemberID     int64
	CodeHash     []byte
	RequestHash  []byte
	ExpiresAt    string
	AttemptsLeft int64
}

type Member struct {
	ID          int64
	Email       sql.NullString
	DisplayName sql.NullString
	Status      string
	AddedAt     string
	AddedBy     sql.NullInt64
	RevokedAt   sql.NullString
	RevokedBy   sql.NullInt64
}

type Session struct {
	ID           int64
	TokenHash    []byte
	MemberID     int64
	OpenedAt     string
	LastActiveAt string
	ExpiresAt    string
	DeviceType   string
	Os           string
	Browser      string
	InstalledApp int64
	Label        sql.NullString
}

type Tribe struct {
	ID   int64
	Name string
}
