// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tribedb

import (
	"database/sql"
)

type AuditLog struct {
	ID             int64
	At             string
	Operation      string
	MemberID       int64
	AuthorID       sql.NullInt64
	SessionID      sql.NullInt64
	DetectedDevice sql.NullString
}

type Member struct {
	ID          int64
	Email       sql.NullString
	DisplayName sql.NullString
	Status      string
	AddedAt     string
	AddedBy     sql.NullInt64
	RevokedAt   sql.NullString
	RevokedBy   sql.NullInt64
}

type Tribe struct {
	ID   int64
	Name string
}
