// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package tribedb

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (token_hash, member_id, opened_at, last_active_at, expires_at, device_type, os, browser, installed_app)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSessionParams struct {
	TokenHash    []byte
	MemberID     int64
	OpenedAt     string
	LastActiveAt string
	ExpiresAt    string
	DeviceType   string
	Os           string
	Browser      string
	InstalledApp int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.TokenHash,
		arg.MemberID,
		arg.OpenedAt,
		arg.LastActiveAt,
		arg.ExpiresAt,
		arg.DeviceType,
		arg.Os,
		arg.Browser,
		arg.InstalledApp,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const memberSessions = `-- name: MemberSessions :many
SELECT id, token_hash, member_id, opened_at, last_active_at, expires_at, device_type, os, browser, installed_app, label FROM sessions WHERE member_id = ? ORDER BY id
`

func (q *Queries) MemberSessions(ctx context.Context, memberID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, memberSessions, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.MemberID,
			&i.OpenedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.DeviceType,
			&i.Os,
			&i.Browser,
			&i.InstalledApp,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeSessions = `-- name: PurgeSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) PurgeSessions(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionByID = `-- name: SessionByID :one
SELECT id, token_hash, member_id, opened_at, last_active_at, expires_at, device_type, os, browser, installed_app, label FROM sessions WHERE id = ?
`

func (q *Queries) SessionByID(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, sessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.MemberID,
		&i.OpenedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.DeviceType,
		&i.Os,
		&i.Browser,
		&i.InstalledApp,
		&i.Label,
	)
	return i, err
}

const sessionByTokenHash = `-- name: SessionByTokenHash :one
SELECT id, token_hash, member_id, opened_at, last_active_at, expires_at, device_type, os, browser, installed_app, label FROM sessions WHERE token_hash = ? AND expires_at > ?
`

type SessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt string
}

func (q *Queries) SessionByTokenHash(ctx context.Context, arg SessionByTokenHashParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, sessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.MemberID,
		&i.OpenedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.DeviceType,
		&i.Os,
		&i.Browser,
		&i.InstalledApp,
		&i.Label,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_active_at = ?, expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastActiveAt string
	ExpiresAt    string
	ID           int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastActiveAt, arg.ExpiresAt, arg.ID)
	return err
}
