// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tribe.sql

package tribedb

import (
	"context"
)

const insertTribe = `-- name: InsertTribe :exec
INSERT INTO tribe (id, name) VALUES (1, ?)
`

func (q *Queries) InsertTribe(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, insertTribe, name)
	return err
}

const tribeName = `-- name: TribeName :one
SELECT name FROM tribe WHERE id = 1
`

func (q *Queries) TribeName(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, tribeName)
	var name string
	err := row.Scan(&name)
	return name, err
}
